import React from 'react';

const TermsConditions = () => (
    <h1>
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
        YOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOMEYOUBELONGTOME
    </h1>
);

export default TermsConditions;